AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Resources:

  Yelpinbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'yelp-input-data-g3'