name: Deploy Yelp Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      GlueJobScriptLocation:
        description: 'S3 location of the Glue job script'
        required: true
      GlueJobNumWorkers:
        description: 'Number of Glue job workers'
        required: true

jobs:
  cft_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name yelpresource \
            --template-file .github/workflows/TrialCFT2.yml  # Adjust the path as needed
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              GLUE_JOB_SCRIPT=${{ secrets.GLUE_JOB_SCRIPT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # - name: Upload Script to S3 Bucket
      #   run: |
      #     aws s3 cp script.py s3://bdata-script/

      # - name: Dump raw data to S3
      #   run: |
      #     aws s3 cp s3://yelp-raw-data/ s3://yelp-input-data-g3/ --recursive
